<!-- <div class="sp_new_service_request">
    <div>
        <p>Service Area</p>
        <select name="" id="">
            <option value="">25</option>
        </select>
    </div>
    <div>
        <input type="checkbox">
        <label for="">including pet at home</label>
    </div>    
</div> -->
<table id="sp_new_services_table">
    <thead>
        <tr>
            <th>Service Id</th>
            <th>Service Date</th>
            <th>Customer Details</th>
            <th>Payment</th>
            <!-- <th>Time Conflict</th> -->
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <!-- GENERATED BY DATATABLE -->
    </tbody>
</table>

<!-- **********NEW-SERVICE-REQUEST********** -->
<script>
    $(document).ready(function(){
        store.service_provider.table.new_services = $('#sp_new_services_table').DataTable({
            searching : false,
            serviceSide : true,
            autoWidth : false,
            dom : 't<"datatable_bottom"lp>',
            ajax : {
                url : `${BASE_URL}/service-provider/service/new`,
                cache : true,
                dataSrc : function(data){
                    store.service_provider.data.new_services = data;
                    return data;
                },
            },
            columns :[
                {
                    render : function(data, type, row){
                        return`<p class="service_id" onclick="show_service_details(${row.Service.Id})">${row.Service.Id}</p>`;
                    },
                },
                {
                    render : function(data, type, row){
                        return `<div class="service_date" onclick="show_service_details(${row.Service.Id})">
                                    <div>
                                        <img src="<?= assets('assets/img/table/calendar.png'); ?>" alt="">
                                        <p>${row.Service.ServiceDate}</p>
                                    </div>
                                    <div>
                                        <img src="<?= assets('assets/img/table/time.png'); ?>" alt="">
                                        <p>${row.Service.StartTime} to ${row.Service.EndTime}</p>
                                    </div>
                                </div>`;
                    }
                },
                {
                    render : function(data, type, row){
                        return `<div class="customer_details" onclick="show_service_details(${row.Service.Id})"> 
                                    <p>${row.Customer.Name}</p>
                                    <div>
                                        <img src="<?= assets('assets/img/table/home.png'); ?>" alt="">
                                        <p>${row.ServiceAddress.AddressLine1} ${row.ServiceAddress.AddressLine2}, ${row.ServiceAddress.PostalCode} ${row.ServiceAddress.City}</p>
                                    </div>
                                </div>`;
                    }
                },
                {
                    render : function(data, type, row){
                        // €
                        return `<p class="payment_text" onclick="show_service_details(${row.Service.Id})">€<span>${row.Service.TotalCost}</span></p>`;
                    }
                },
                {
                    render : function(data, type, row){
                        return `<div style="display:flex;">
                                    <button class="accept_btn" onclick="accept_service_open_model(${row.Service.Id})">Accept</button>
                                </div>`;
                    }
                }
            ],
            pagingType : 'full_numbers',
            language : {
                paginate : {
                    first    :'<i class="fa-solid fa-backward-step"></i>',
                    previous :'<i class="fas fa-angle-left">',  
                    next     :'<i class="fas fa-angle-right">',
                    last     :'<i class="fa-solid fa-forward-step"></i>'  
                },
            }
        });
    });
</script>

<!-- **********ACCEPT-SERVICE********** -->
<script>
    // SETUP HTML FOR ACCEPT SERVICE POPUP...
    
    function accept_service_open_model(id){
        // $€
        let data = store.service_provider.data.new_services.filter((i)=>{
            if(i.Service.Id==id){
                return i;
            }
        });
        data = data[0];

        // FOR ACCEPT SERVICE ID STORE GLOBALLY...
        store.id.accept = data.Service.Id;

        $('#accept_service_request_popup').html(`
            <p class="popup_title">Service Details</p>
            <div class=""><!-- FIRST DIV -->
                <div>
                    <p>${data.Service.ServiceDate} | ${data.Service.StartTime} - ${data.Service.EndTime}</p>
                    <p>Duration : <span>${data.Service.Duration} Hours</span></p>
                </div>
                <div>
                    <p>Service Id : <span>${data.Service.Id}</span></p>
                    ${(function(){
                        let extraService = ``;
                        if(data.Service.ExtraService!==null){
                            for(let i=0; i<data.Service.ExtraService.length; i++){
                                if(data.Service.ExtraService[i]==1){
                                    extraService += `<p>Extras : <span>Inside Cabinet</span></p>`;
                                }
                                else if(data.Service.ExtraService[i]==2){
                                    extraService += `<p>Extras : <span>Inside Fridge</span></p>`;
                                }
                                else if(data.Service.ExtraService[i]==3){
                                    extraService += `<p>Extras : <span>Inside Oven</span></p>`;
                                }
                                else if(data.Service.ExtraService[i]==4){
                                    extraService += `<p>Extras : <span>Inside Laundry</span></p>`;
                                }
                                else if(data.Service.ExtraService[i]==5){
                                    extraService += `<p>Extras : <span>Inside Window</span></p>`;
                                }
                            }
                            return extraService;
                        }
                        else{
                            return extraService;                            
                        }
                    })()}
                    <p>Total Amount : <span class="payment_text">€${data.Service.TotalCost}</span></p>
                </div>
                <div>
                    <p>Customer Name : <span>${data.Customer.Name}</span></p>
                    <p>Service Address : <span>${data.ServiceAddress.AddressLine1} ${data.ServiceAddress.AddressLine2}, ${data.ServiceAddress.PostalCode} ${data.ServiceAddress.City} </span></p>
                    <!-- <p>Distance : <span>296km</span></p>-->
                </div>
                <div>
                    <p>Conmments : <span>${data.Service.Comments?data.Service.Comments : ''}</span></p>
                </div>
                <div class="table_btn_container">
                    <button class="accept_btn" onclick="accept_service()"><i class="fas fa-check"></i>Accept</button>
                </div>		
            </div>
            <div><!-- SECOND DIV FOR MAP -->
                <img src="<?= assets('assets/img/static/contact/section_2/map.png'); ?>" alt="">
            </div>
        `);
        open_model('accept_service_request');
    }
</script>
