<table id="sp_upcoming_services_table">
    <thead>
        <tr>
            <th>Service Id</th>
            <th>Service Date</th>
            <th>Customer Details</th>
            <th>Distance</th>
            <th>Actions</th>    
        </tr>
    </thead>
    <tbody>
        <!-- GENERATED BY DATATABLE -->
    </tbody>
</table><!-- END_UPCOMING_SERVICE -->


<!-- **********SP-UPCOMING-SERVICE-REQUEST********** -->
<script>
    $(document).ready(function(){
        store.service_provider.table.upcoming_services = $('#sp_upcoming_services_table').DataTable({
            searching : false,
            serviceSide : true,
            autoWidth : false,
            dom : 't<"datatable_bottom"lp>',
            ajax : {
                url : `${BASE_URL}/service-provider/service/upcoming`,
                cache : true,
                dataSrc : function(data){
                    store.service_provider.data.upcoming_services = data;
                    return data;
                },
            },
            columns :[
                {
                    render : function(data, type, row){
                        return`<p class="service_id" onclick="show_service_details(${row.Service.Id})">${row.Service.Id}</p>`;
                    },
                },
                {
                    render : function(data, type, row){
                        return `<div class="service_date" onclick="show_service_details(${row.Service.Id})">
                                    <div>
                                        <img src="<?= assets('assets/img/table/calendar.png'); ?>" alt="">
                                        <p>${row.Service.ServiceDate}</p>
                                    </div>
                                    <div>
                                        <img src="<?= assets('assets/img/table/time.png'); ?>" alt="">
                                        <p>${row.Service.StartTime} - ${row.Service.EndTime}</p>
                                    </div>    
                                </div>`;
                    }
                },
                {
                    render : function(data, type, row){
                        return `<div class="customer_details" onclick="show_service_details(${row.Service.Id})">
                                    <p>${row.Customer.Name}</p>
                                    <div>
                                        <img src="<?= assets('assets/img/table/home.png'); ?>" alt="">
                                        <p>${row.ServiceAddress.AddressLine1} ${row.ServiceAddress.AddressLine2}, ${row.ServiceAddress.PostalCode} ${row.ServiceAddress.City}</p>
                                    </div>
                                </div>`;
                    }
                },
                {
                    render : function(data, type, row){
                        return ``;
                    }
                },
                {
                    render : function(data, type, row){
                        if(row.Service.IsExpired==1 && row.Service.Status==1){
                            return `<div class="table_btn_container">
                                        <button class="accept_btn" onclick="complete_service(${row.Service.Id})">Complete</button>
                                        <button class="cancel_btn" onclick="reject_service_by_sp(${row.Service.Id})">Cancel</button>
                                    </div>`;
                        }
                        else{
                            return `<div class="table_btn_container">
                                        <button class="cancel_btn" onclick="reject_service_by_sp(${row.Service.Id})">Cancel</button>
                                    </div>`;
                        }
                    }
                }
            ],
            pagingType : 'full_numbers',
            language : {
                paginate : {
                    first    :'<i class="fa-solid fa-backward-step"></i>',
                    previous :'<i class="fas fa-angle-left">',  
                    next     :'<i class="fas fa-angle-right">',
                    last     :'<i class="fa-solid fa-forward-step"></i>'  
                },
            }
        });
    });
</script>

<!-- **********REJECT-SERVICE-SERVICE-BY-SP********** -->
<script>
    function reject_service_by_sp(id){
        Swal.fire({
            title : 'Are you sure?',
            showCancelButton: true, 
            icon : 'warning'
        }).then((res)=>{
            if(res.isConfirmed){
                $.ajax({
                    url : `${BASE_URL}/service-provider/service/reject/${id}`,
                    method : 'PATCH',
                    success : function(res){
                        if(res!=="" && res!==undefined){
                            try{
                                const result = JSON.parse(res);
                                Swal.fire({
                                    title : result.message,
                                    icon : 'success'
                                });
                                close_model();
                                store.service_provider.table.upcoming_services.ajax.reload();
                            }
                            catch(e){
                                Swal.fire({
                                    title : 'Invalid JSON Response!',
                                    icon : 'error'
                                })
                            }
                        }
                    }
                });
            }
        });
    }
</script>