<div class="your_details">
    <!-- ADDRESS INFORM OF RADIO BUTTON -->
    <div class="label_input">
        <label class="label" for="">Enter your contact details so we can serve you in better way!</label>
        <div id="user_radio_address_container">
            <!-- GENERATED BY JAVASCRIPT -->
        </div>
        <button class="book_service_outline_btn" id="open_address_form_btn"><i class="fas fa-plus"></i>Add Address</button>
        <!-- ADDRESS FORM AUTOMETIC FILL BY CHOOSE A RADIO BUTTON -->
        <form class="address_form d_none" id="address_form">
            <div class="label_input">
                <label class="label" for="">Street Name</label>
                <input class="input" type="text" name="address_form_street_name">
                <div class="validation_message d_none">
                    <p>Validation Message</p>
                </div>
            </div>
            <div class="label_input">
                <label class="label" for="">House Number</label>
                <input class="input" type="text" name="address_form_house_number">
                <div class="validation_message d_none">
                    <p>Validation Message</p>
                </div>
            </div>
            <div class="label_input">
                <label class="label" for="">Postal Code</label>
                <input class="input" type="text" name="address_form_postal_code">
                <div class="validation_message d_none">
                    <p>Validation Message</p>
                </div>
            </div>
            <div class="label_input">
                <label class="label" for="">City</label>
                <input class="input" type="text" name="address_form_city">
                <div class="validation_message d_none">
                    <p>Validation Message</p>
                </div>
            </div>
            <div class="label_input">
                <label class="label" for="">Phone Number</label>
                <div class="phone_number">
                    <label for="">+49</label>
                    <input type="text" name="address_form_phone">
                </div>
                <div class="validation_message d_none">
                    <p>Validation Message</p>
                </div>
            </div>
            <div>
                <button class="book_service_btn">Save</button>
                <button class="book_service_outline_btn" id="close_address_form_btn">Cancel</button>
            </div>
        </form>								
    </div>
    <div>
        <label class="label" for="">Your Favourite Service Providers</label>
        <p>You can choose your favourite service provider from the below list</p>
        <!-- LIST OF SERVICE PROVIDER -->
        <div id="favourite_sp_container">
            <!-- GENERATED BY JAVASCRIPT -->
        </div>
    </div>
    <div class="validation_message d_none">
        <p>Validation Message</p>
    </div>
    <button id="your_details_submit_btn" class="book_service_btn">Continue</button>
</div>

<!-- **********LOAD ADDRESS********** -->
<script>
    function load_user_address(){
        $.ajax({
            url : `${BASE_URL}/user/address`,
            method : 'GET',
            success : function(res){
                if(res!=="" && res!==undefined){
                    try{
                        store.customer.address = JSON.parse(res);
                        $('#user_radio_address_container').html(`${(function(){    
                            let html = '';
                            store.customer.address.forEach((i)=>{
                                html += `
                                <div class="radio_address">
                                    <input type="radio" id="radio_address_${i.AddressId}" name="service_booking_address" value="${i.AddressId}">
                                    <label for="radio_address_${i.AddressId}">
                                        <div>
                                            <p><span>Address</span> : ${i.AddressLine1} ${i.AddressLine2}, ${i.PostalCode}, ${i.City}</p>
                                            <p><span>Phone Number</span> : ${i.Mobile}</p>
                                        </div>
                                    </label>
                                </div>`;
                            });
                            return html;
                        })()}`);
                    }
                    catch(e){
                        console.log('Invalid JSON Reponse!');
                        Swal.fire({
                            title:'Interal Server Error',
                            text:'Invalid JSON Response!',
                            icon:'error'
                        });
                    }
                }
            }
        });
    }
    load_user_address();

    // ON CHANGE STORE ADDRESS ON GLOBAL OBJECT...
    $('[name="service_booking_address"]').change(function(){
        addressId = parseInt($('[name="service_booking_address"]:checked').val());
        store.bookService.address.filter((obj)=>{
            if(obj.AddressId==addressId){
                store.bookService.address = obj;
            }
        });
    });
</script>

<!-- **********LOAD FAVORITE SP********** -->
<script>
    function load_favorite_sp(){
        $.ajax({
            url : `${BASE_URL}/book-service/customer/favorite-sp`,
            method : 'GET',
            success : function(res){
                if(res!=="" && res!==undefined){
                    try{
                        const result = JSON.parse(res);
                        $('#favourite_sp_container').html(`${(function(){
                            let html = ``;
                            for(let i=0; i<result.length; i++){
                                html += `<div class="form_group">
                                            <input type="radio" id="favourite_sp${result[i].UserId}" name="favourite_sp" value="${result[i].UserId}">
                                            <label class="your_details_sp_card" for="favourite_sp${result[i].UserId}">
                                                <img src="${BASE_URL}/assets/img/avatar/${result[i].UserProfilePicture}.png" alt="">
                                                <p>${result[i].FirstName} ${result[i].LastName}</p>
                                                <p class="book_service_outline_btn">Select</p>
                                            </label>	
                                        </div>`;
                            }
                            return html;
                        })()}`);
                    }
                    catch(e){
                        console.log('Invalid JSON Response!');
                    }
                }
            }
        });
    }
    load_favorite_sp()

    // ON CHANGE STORE FAVORITE SP ON GLOBAL OBJECT...
    $('[name="favourite_sp"]').change(function(){
        store.bookService.serviceProviderId = parseInt($('[name="favourite_sp"]:checked').val());
    });

</script>

<!-- **********ADD ADDRESS********** -->
<script>
    // [postalcode, mobile] BEFORE OPENING ADDRESS FORM PRE SET VALUE...
    $('#open_address_form_btn').click(function(){
        $('[name="address_form_postal_code"]').val(store.bookService.postalCode);
        if(store.loggedUserDetails.Mobile!==null){
            $('[name="address_form_phone"]').val(store.loggedUserDetails.Mobile);
        }
    })

    $('#address_form').submit((e)=>{
        e.preventDefault();
        let validation = true;
        const validationArr = [address_form_street_name_validation(),
                               address_form_house_number_validation(),
                               address_form_postal_code_validation(),
                               address_form_city_validation(),
                               address_form_phone_validation()];

        for(let i=0; i<validationArr.length; i++){
            if(validationArr[i]==false){
                validation = false;
                break;
            }
        }

        if(validation){

            const json = JSON.stringify({
                streetName : $('[name="address_form_street_name"]').val(),
                houseNumber : $('[name="address_form_house_number"]').val(),
                postalCode : $('[name="address_form_postal_code"]').val(),
                city : $('[name="address_form_city"]').val(),
                phone : $('[name="address_form_phone"]').val(),
            });

            $.ajax({
                url : `${BASE_URL}/user/address`,
                method : 'POST',
                contentType : 'application/json',
                data : json,
                success : function(res){
                    if(res!==""){
                        $('#address_form').trigger('reset');
                        address_form_toggle();
                        load_user_address();
                        Swal.fire({
                            'title':'Good Job',
                            'text':'Address Added Successfully.',
                            'icon':'success'
                        });
                    }
                }
            });
        }
    });

</script>

<!-- **********BOOK-SERVICE-S3********** -->
<script>
    // SECTION-3-BTN-CLICK...
    $('#your_details_submit_btn').click(function(){
        // SERVICE BOOKING ADDRESS...
        let validation = book_service_address_validation();
        if(validation){
            addressId = parseInt($('[name="service_booking_address"]:checked').val());
            store.customer.address.filter((obj)=>{
                if(obj.AddressId==addressId){
                    store.bookService.address = obj;
                }
            });
            
            // DIRECT ASSSIGNMENT TO THE SERVICE PROVIDER...
            if($('[name="favourite_sp"]:checked').val()!==""){
                store.bookService.serviceProviderId = parseInt($('[name="favourite_sp"]:checked').val());
            }
            else{
                store.bookService.serviceProviderId = null;
            }
            change_book_service_tabs(3);
        }
    });
</script>

